---
title: "descriptives02"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
# knitr opts
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
# packages
library(tidyverse)
library(sf)
library(mapview)
library(leaflet)
library(leafem)
library(leafpop)
library(leafsync)
library(plotly)
library(shiny)
library(shinyWidgets)
library(lubridate)
library(dygraphs)
library(xts)

processed   <- "/Volumes/Al-Hakem-II/Datasets/bks/bks"
days    <- readRDS(file.path(processed, "data/plato/days.Rda"))
#bks     <- readRDS(file.path(processed, "data/plato/daily-rides.Rda"))
sum_station <- readRDS(file.path(processed, "data/plato/sum-station.Rda")) %>%
  select(-starts_with("lag")) # remove lag vars, not needed here.
  
sum_station_yr <- readRDS(file.path(processed, "data/plato/sum-station-yr.Rda")) %>%
select(-starts_with("lag"))  # remove lag vars, not needed here.


# document/package settings
theme_set(theme_minimal()) # set ggplot theme
mapviewOptions(fgb = T) # set to false for greater performance?
alpha = 0.2
```

Thanks to RColorBrewer for providing the color scales.

# Days

```{r}
inputPanel(
  selectInput('y1', "Y Axis", 
              choices = c("Number of Rides"      =  "nrides",
                          "Median Ride Duration" =  "dur_med",
                          "Duration Inequity"    =  "dur_ineq"),
              selected = "nrides",  multiple = FALSE, selectize = TRUE)
) 

# convert date to xts 
data1 <- reactive({
  days %>% ungroup() %>%
  select(date, input$y1) %>% # keep only the date and y1
  as.xts(.$date)
})

# make the graph
renderDygraph({
dygraph(data1(), main = "System Data") %>% 
  dyRangeSelector(height=20) %>%
  dyAxis('x', axisLabelFontSize = 12) %>%
  dyOptions(fillGraph = TRUE, fillAlpha = 0.4)  
})
```

# Stations

## Yearly Departures

```{r, echo=FALSE}
inputPanel(
  sliderInput('year2', "Year", 2010, 2020, 2010, sep = '', ticks = FALSE),
  selectInput('y2', "Y Axis", 
              choices = c("Number of Rides"      =  "departures",
                          "Median Ride Duration" =  "dur_med",
                          "Departure Inequity"   =  "dep_ineq",
                          "Near Metro"           =  "metro",
                          "Percent of Rides to Metro" = "metro_end_pct",
                          "Member Percent"       = "member_pct",
                          "Net Flow"             = "net_flow",
                          "Net Median Duration"  = "net_median_dur"),
              selected = "departures",  multiple = FALSE, selectize = TRUE),
  materialSwitch('scaled', "Scaled", value = FALSE)
)

pal2  <- reactive({
  if (input$scaled == FALSE) {
    colorQuantile("YlOrRd", sum_station_yr$input$y2, 5)
  } else {
    colorNumeric("YlOrRd", sum_station_yr$input$y2)
  }
  })
data2 <- reactive({ filter(sum_station_yr, year == input$year2) })

m2 <- reactive({
  leaflet(data = data2(), height = 800) %>%
  addTiles() %>%
  addCircleMarkers(color = ~pal2()(eval(as.symbol(input$y2))),
                   fillColor = ~pal2()(eval(as.symbol(input$y2))),
                   radius=7, stroke = TRUE, weight = 2,
                   opacity = 0.9, fillOpacity = 0.4, 
                   label = ~eval(as.symbol(input$y2)),
                   popup = ~name_bks_st) # add legend later, lol
})
  
renderLeaflet({m2()})



# data1 <- reactive({ filter(sum_station_yr, year == input$year1) })
# m1 <- reactive({
#   mapview(data1(), zcol = "departures",
#           at = c(0,1000,2000,5000,10000,20000,100000)
#           )
#   })
# 
# renderLeaflet({
#     m1()@map
# })


```

## Daily Departures

Note the interpretation is in terms of average or summed station-days over the time period specified.

```{r, echo=FALSE}
inputPanel(
  dateRangeInput('dt3a',"Date A","2010-01-01","2020-12-31", startview = "year"),
  dateRangeInput('dt3b',"Date B","2010-01-01","2020-12-31", startview = "year"),
  selectInput('y3', "Y Axis", 
              choices = c("Number of Rides"      =  "departures",
                          "Median Ride Duration" =  "dur_med",
                          "Departure Inequity"   =  "dep_ineq",
                          "Percent of Rides to Metro" = "metro_end_pct",
                          "Member Percent"       = "member_pct",
                          "Net Flow"             = "net_flow"),
              selected = "departures",  multiple = FALSE, selectize = TRUE),
  materialSwitch('scaled3', "Scaled", value = FALSE)
)

# summarize/filter dataframe based on date range.
int3a  <- reactive({ interval(start = input$dt3a[1], end = input$dt3a[2]) }) 
data3a <- reactive({ 
  sum_station %>% filter(date %within% int3a() ) %>%
    dplyr::ungroup() %>% group_by(id_station, name_bks, lat, lng) %>%
    summarise(
      departures    = round(mean(departures, na.rm=T), 1),
      dur_med       = round(mean(dur_med, na.rm=T) / 60, 1),
      dep_ineq      = round(mean(dep_ineq, na.rm=T), 3),
      metro_end_pct = round(mean(metro_end_pct, na.rm=T), 3),
      member_pct    = round(mean(member_pct, na.rm=T), 3),
      net_flow      = sum(net_flow)
    )
  })

int3b  <- reactive({ interval(start = input$dt3b[1], end = input$dt3b[2]) }) 
data3b <- reactive({ 
  sum_station %>% filter(date %within% int3b() ) %>%
    dplyr::ungroup() %>% group_by(id_station, name_bks, lat, lng) %>%
    summarise(
      departures    = round(mean(departures, na.rm=T), 1),
      dur_med       = round(mean(dur_med, na.rm=T) / 60, 1),
      dep_ineq      = round(mean(dep_ineq, na.rm=T), 3),
      metro_end_pct = round(mean(metro_end_pct, na.rm=T), 3),
      member_pct    = round(mean(member_pct, na.rm=T), 3),
      net_flow      = sum(net_flow)
    )
  })


pal3  <- reactive({
  if (input$scaled3 == FALSE) {
    colorQuantile("YlOrRd", sum_station$input$y3, 5)
  } else {
    colorNumeric("YlOrRd", sum_station$input$y3)
  }
  })

m3a <- reactive({
  leaflet(data = data3a(), height = 800) %>%
  addTiles() %>%
  addCircleMarkers(color = ~pal3()(eval(as.symbol(input$y3))),
                   fillColor = ~pal3()(eval(as.symbol(input$y3))),
                   radius=7, stroke = TRUE, weight = 2,
                   opacity = 0.9, fillOpacity = 0.4, 
                   label = ~eval(as.symbol(input$y3)),
                   popup = ~name_bks) # add legend later, lol
})

m3b <- reactive({
  leaflet(data = data3b(), height = 800) %>%
  addTiles() %>%
  addCircleMarkers(color = ~pal3()(eval(as.symbol(input$y3))),
                   fillColor = ~pal3()(eval(as.symbol(input$y3))),
                   radius=7, stroke = TRUE, weight = 2,
                   opacity = 0.9, fillOpacity = 0.4, 
                   label = ~eval(as.symbol(input$y3)),
                   popup = ~name_bks) # add legend later, lol
})
  
#test <- reactive({ sync( m3a(), m3b() ) })

renderLeaflet({ m3a() })
renderLeaflet({ m3b() })



```
